Added Responsiveness to Contact Page
chiraag-kakar/sharenlearn pull request #168
Opened 2021-04-09 13:53 UTC by Devender00999

Updated Contact page

2021-04-09 14:08 UTC, Devender00999 commented
# Issue: #168 
## Description
Contact page was not responsive & It was showing big buttons and input boxes. So I have added responsiveness to it.
# Screenshots
![SS1](https://user-images.githubusercontent.com/37322572/114191384-f969ac00-9969-11eb-89e4-52a33f39d719.jpeg)
![SS2](https://user-images.githubusercontent.com/37322572/114191388-fb336f80-9969-11eb-85d7-a00292d6c706.jpeg)
![SS3](https://user-images.githubusercontent.com/37322572/114192417-13f05500-996b-11eb-885e-ab6c04739432.jpeg)

2021-04-10 15:36 UTC, harshita2216 requested changes
Hey @Devender00999 , could you please decrease the size of the image in mobile view. I think it would look better that way. :)

2021-04-10 16:46 UTC, Devender00999 commented
> Hey @Devender00999 , could you please decrease the size of the image in mobile view. I think it would look better that way. :)

Done

2021-04-18 06:20 UTC, harshita2216 approved these changes

2021-04-25 10:38 UTC, merged